version: '3.3'
services:
  # ###########################################################################
  # Jenkins container. 
  # ###########################################################################
  jenkins:
    image: jenkins/jenkins:alpine
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
    networks:
      - jenkins-workers
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.05'
          memory: 50M

  # ###########################################################################
  # Jenkins docker worker node.
  # ###########################################################################
  parsoid:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - COMMAND_OPTIONS="-master http://jenkins -username admin -password admin -labels 'docker-dev' -executors 5"
    networks:
      - jenkins-workers
    volumes:
      - type: bind
      - source: /var/run/docker.sock
      - target: /var/run/docker.sock
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.01'
        reservations:
          cpus: '0.001'
          memory: 20M


volumes:
  jenkins_home:

networks:
  jenkins-workers:
    driver: overlay
    internal: true