version: '3.3'
services:
  # ###########################################################################
  # The GCpedia container.  Will be accessible at http://localhost:8080
  # ###########################################################################
  gcpedia:
    image: phanoix/gcpedia
    ports:
      - 8800:80
    volumes:
      - type: volume
        source: gcpedia_images
        target: /var/www/html/docker_gcpedia/images
    networks:
      - gcpedia-services
    deploy:
      replicas: 1
      resources:
          limits:
            cpus: '0.8'
          reservations:
            cpus: '0.1'
            memory: 250M
      restart_policy:
        condition: on-failure
#  use this if gcpedia has already been installed and LocalSettings.php config created
#    configs:
#      - source: LocalSettings.php
#        target: /var/www/html/docker_gcpedia/LocalSettings.php
#        mode: 0444
    environment:
      - DOCKER=1
      - DBHOST=gcpedia-db
      - HOST=gcpedia.tools.gc.ca
      - PORT=8800
# for single signon with GCconnex
#      - USESAML=true


  # ###########################################################################
  # The parsoid container for the VisualEditor.
  # Will be available to gcpedia at parsoid:8142
  # ###########################################################################
  parsoid:
    image: phanoix/parsoid
    networks:
      - gcpedia-services
    deploy:
      replicas: 1
      resources:
          limits:
            cpus: '0.1'
            memory: 250M
          reservations:
            cpus: '0.01'
            memory: 50M
      restart_policy:
        condition: on-failure

  # ###########################################################################
  # The Electron render service container for the ElectronPdfService Extension.
  # Will be available to gcpedia at elec-render:3000
  # ###########################################################################
  elec-render:
    image: msokk/electron-render-service
    networks:
      - gcpedia-services
    deploy:
      replicas: 1
      resources:
          limits:
            cpus: '0.1'
            memory: 250M
          reservations:
            cpus: '0.01'
            memory: 50M
    restart_policy:
      condition: on-failure

  # ###########################################################################
  # Database container for gcpedia, accessible from by the gcpedia container 
  # using the network host "gcpedia-db".
  # ###########################################################################
  gcpedia-db:
    image: library/mariadb:10.3
    volumes:
      - type: volume
        source: gcpedia_db
        target: /var/lib/mysql
    networks:
      - gcpedia-services
    deploy:
      replicas: 1
      resources:
          limits:
            cpus: '0.8'
          reservations:
            cpus: '0.2'
            memory: 500M
      restart_policy:
        condition: always
    environment:
      - MYSQL_ROOT_PASSWORD=gcpedia
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=gcpedia
      
volumes:
  gcpedia_db:
  gcpedia_images:

networks:
  gcpedia-services:
    driver: overlay
    internal: true
