version: '2'
services:
  # ###########################################################################
  # The GCpedia container.  Will be accessible at http://localhost:8080
  # ###########################################################################
  gcpedia:
    build: .
    ports:
      - 8800:80
    volumes:
      - .:/var/www/html/docker_gcpedia
      - ./images:/var/www/html/docker_gcpedia/images
      - /var/www/html/docker_gcpedia/vendor
    links:
      - gcpedia-db
    depends_on:
      - gcpedia-db
    environment:
      - DOCKER=1
      - DBHOST=gcpedia-db
      - HOST=wiki.gccollab.ca
      - PORT=
      - OPENID=true
#      - OAUTH=true
#      - USESAML=false

  # ###########################################################################
  # The parsoid container for the VisualEditor.
  # Will be available to gcpedia at parsoid:8142
  # ###########################################################################
  parsoid:
    build:
      context: .
      dockerfile: Dockerfile.parsoid
    ports:
      - 8142:8000

  # ###########################################################################
  # The Electron render service container for the ElectronPdfService Extension.
  # Will be available to gcpedia at elec-render:3000
  # ###########################################################################
 # elec-render:
 #   image: msokk/electron-render-service
 #   ports:
 #     - 3000:3000

  # ###########################################################################
  # Database container for gcpedia, accessible from by the gcpedia container 
  # using the network host "gcpedia-db".
  # ###########################################################################
  gcpedia-db:
    image: library/mariadb:10.3
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gcpedia
      - MYSQL_DATABASE=wiki
      - MYSQL_USER=wiki
      - MYSQL_PASSWORD=gcpedia